### PR TITLE
Added syntax color to the documentation

### PR DESCRIPTION
**Pull request by Davidazullo**

### CODE REVIEW

**Comment by GrosSacASac** [comment]
Please not someone is already doing it https://github.com/GrosSacASac/DOM99/pull/8 it seems

**Comment by Davidazullo** [comment]
Ok I see, by the way I already modified all the code tags and added a library to colorize the codeblocks if it helps.

**Comment by GrosSacASac** [comment]
> `<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>`

https://rawgit.com/ is ending see blog post https://rawgit.com/

**Comment by GrosSacASac** [comment]
<script nomodule src="./deps/template.js"></script>
<script nomodule src="./deps/template-mb-bootstrap.js"></script>
<script nomodule src="js/documentation.es5.min.js"></script>

why did you remove those ?

**Comment by Davidazullo** [comment]
Sorry for my mistake @GrosSacASac, I deleted these lines by error, it should be fine now :).

**Comment by GrosSacASac** [comment]
(merge from master) then edit documentation-original.html instead of documentation.html,

**Comment by GrosSacASac** [comment]
Closed in favor of https://github.com/GrosSacASac/DOM99/pull/17, do not hesitate do open another issue if you think your approach is better

**Pull request closed without merging**
