### PR TITLE
Added code highlight for documentation page

### PR DESCRIPTION
**Pull request by RobqFakulcik**
For issue: https://github.com/GrosSacASac/DOM99/issues/3#issue-369847652

### CODE REVIEW

**Comment by GrosSacASac** [comment]
Ok looks good.
Could you edit documentation-original.html instead

**Comment by RobqFakulcik** [comment]
> Ok looks good.
> Could you edit documentation-original.html instead

Not sure if its still actual.
Cause of this:
[#10](https://github.com/GrosSacASac/DOM99/pull/10#issue-222682797)
Let me know...

**Comment by GrosSacASac** [comment]
If you both complete approved PR, then I will take the one that looks better

**Comment by RobqFakulcik** [comment]
OK, I was moved code highlight to documentation-original.html file, as you wish.

**Comment by GrosSacASac** [comment]
Closing in favor of https://github.com/GrosSacASac/DOM99/pull/17

**Pull request closed without merging**
